import type { InterviewQuestion, InterviewType, InterviewSession } from '../types';

export const LOCAL_MODEL='reqvoice-local-nlp-v1';
const STOP_WORDS=new Set(['the','and','that','this','with','from','have','your','they','their','there','about','would','could','should','what','when','where','which','into','then','than','were','been','being','also','very','just','some','more','system','current','using','used','use','need','needs','want','like','make','does','how','can']);
const TEMPLATES:Record<InterviewType,Array<any>>={
 Structured:[
  ['workflow','What are the exact inputs, validation checks, and outputs in the main workflow?','Map the operational sequence and business rules.',['What validation rules must never be skipped?','Which step creates the most delay?']],
  ['pain_point','How often do failures or manual workarounds occur, and what is their operational impact?','Quantify recurring process problems.',['How much time is lost?','What happens when the process fails?']],
  ['expectation','What measurable response-time, availability, and accuracy targets should the system meet?','Capture measurable non-functional requirements.',['What is the maximum acceptable delay?','What uptime target is required?']],
  ['limitation','What technical, policy, data, or integration constraints limit the current process?','Identify hard boundaries and dependencies.',['Which dependency causes the largest constraint?','Are there regulatory or security limits?']],
  ['desired_feature','Which three capabilities are mandatory for the first release?','Establish an initial acceptance baseline.',['Which capability is a release blocker?','How will success be measured?']]
 ],
 'Semi-Structured':[
  ['workflow','Can you walk me through how you normally complete your main tasks in the system?','Understand the real workflow and user context.',['Which step takes the most effort?','Where do you switch tools?']],
  ['pain_point','What bottlenecks, errors, or manual workarounds frustrate you most?','Expose friction and process weaknesses.',['How often does it happen?','What workaround do you use?']],
  ['expectation','What would make the system faster, easier, and more reliable for your team?','Discover usability and service expectations.',['What response time feels acceptable?','What should be available during network outages?']],
  ['limitation','Where does the current system prevent you from achieving your work goals?','Identify architectural and organizational limits.',['Is the problem technical, procedural, or both?','Which limitation has the biggest effect?']],
  ['desired_feature','If you could add three important capabilities, what would you prioritize?','Capture stakeholder priorities.',['Why is the first feature important?','What would successful adoption look like?']]
 ],
 Unstructured:[
  ['workflow','Tell me about how your work happens from start to finish and where technology fits into it.','Build a broad stakeholder narrative.',['How has this changed over time?','Where do teams collaborate informally?']],
  ['pain_point','What part of the current technology creates the most frustration for your team?','Surface hidden human and operational friction.',['What workaround have you created?','What would you remove first?']],
  ['expectation','If the new system worked exactly the way you wanted, what would your daily work feel like?','Explore the desired future state.',['How would you know the project succeeded?','What would build stakeholder confidence?']],
  ['limitation','What organizational or technology barriers hold your team back today?','Identify systemic constraints.',['Which barrier is hardest to change?','What dependency is outside your control?']],
  ['desired_feature','What innovation would make the biggest meaningful difference in your work?','Gather aspirational capabilities.',['What opportunity would that create?','What should be automated first?']]
 ]};
export function localSuggestQuestions(input:{systemName:string;role?:string;count?:number;interviewType?:InterviewType;language?:string}){const type=input.interviewType||'Semi-Structured';const t=TEMPLATES[type];const count=Math.max(1,Math.min(12,input.count||5));return{questions:Array.from({length:count},(_,i)=>{const x=t[i%t.length]; const tagalog=input.language?.toLowerCase().startsWith('tagalog')||input.language?.toLowerCase()==='tl'; const base=x[1].replace('the system',input.systemName?'the '+input.systemName+' system':'the system'); const tl:Record<string,string>={'Can you walk me through your daily routine workflows and primary tasks in the system?':'Maaari mo bang ilarawan ang iyong pang-araw-araw na workflow at pangunahing gawain sa system?','What are the most frustrating bottlenecks, manual workarounds, or errors you encounter?':'Ano ang mga pinakakainis na bottleneck, manual workaround, o error na nararanasan mo?','What are your core expectations for system latency, accessibility, and user ergonomics?':'Ano ang pangunahing inaasahan mo sa bilis, accessibility, at usability ng system?','Where does the current architecture fail or prevent you from achieving departmental goals?':'Saan nagkukulang ang kasalukuyang architecture o humahadlang sa pagkamit ng mga layunin ng departamento?','If you could prioritize three essential features for the new system, what would they be?':'Kung maaari kang pumili ng tatlong mahalagang feature para sa bagong system, ano ang mga ito?'}; const qText=tagalog?(tl[base]||base):base; return{id:'local-q-'+(i+1),category:x[0],questionText:qText,rationale:(tagalog?'Generated ng lokal na offline requirements model. ':x[2]+' Generated by the local offline requirements model.'),suggestedFollowups:x[3]};}) as InterviewQuestion[]};}
function extractRequirements(text:string){const sentences=text.split(/(?<=[.!?])\s+/).map(s=>s.trim()).filter(Boolean);const marker=/\b(must|should|need to|needs to|required|requirement|shall|able to|allow|support|provide|enable|expect)\b/i;const marked=sentences.filter(s=>marker.test(s));const candidates=marked.length?marked:sentences.filter(s=>/\b(login|report|search|export|approve|notify|backup|security|offline|mobile|performance|integration|database|access)\b/i.test(s));return candidates.slice(0,6).map(s=>s.length>180?s.slice(0,177)+'...':s);}
function localWords(text:string){return text.toLowerCase().replace(/[^a-z0-9\s-]/g,' ').split(/\s+/).filter(w=>w.length>3&&!STOP_WORDS.has(w));}
export function localAnalyzeResponse(input:{text:string;questionText?:string;category?:string;speakerRole?:string}){const text=input.text.trim(),low=text.toLowerCase();const positive=['easy','fast','good','helpful','satisfied','reliable','improve','better','efficient','convenient'];const negative=['slow','error','problem','difficult','frustrating','delay','crash','failure','manual','confusing','pain'];const urgent=['urgent','critical','immediately','asap','severe','cannot','blocked','security breach','outage'];const p=positive.filter(w=>low.includes(w)).length,n=negative.filter(w=>low.includes(w)).length,u=urgent.filter(w=>low.includes(w)).length;const sentiment=(n>p*1.4?'negative':p>n*1.4?'positive':n>0&&p>0?'constructive':'neutral') as 'positive'|'neutral'|'negative'|'constructive';const sentimentScore=Math.max(-1,Math.min(1,(p-n)/Math.max(1,p+n)));const requirements=extractRequirements(text);const counts=localWords(text).reduce<Record<string,number>>((a,w)=>(a[w]=(a[w]||0)+1,a),{});const topics=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([w])=>w);return{sentiment,sentimentScore,sentimentTone:sentiment==='negative'?'Concern / friction':sentiment==='positive'?'Positive / satisfied':sentiment==='constructive'?'Mixed / improvement-oriented':'Neutral',confidence:Math.min(.95,.55+Math.min(.35,text.length/1200)),keyRequirements:requirements.length?requirements:topics.map(t=>'Investigate stakeholder requirement around '+t+'.'),urgency:u?'High':n>=2?'Medium':'Low',analyzedAt:new Date().toISOString(),modelUsed:LOCAL_MODEL};}
export function localRealtimeCopilot(input:{questionText:string;currentAnswer:string;category:string}){return{suggestedFollowUp:input.currentAnswer.trim()?'Can you give a concrete example, frequency, and measurable impact related to that '+input.category.replace(/_/g,' ')+'?':'What is the most important real-world example related to this question?',clarifyingProbe:input.currentAnswer.trim()?'What happens immediately before and after this issue, and who is affected?':'Who performs this task, what information is needed, and what is the expected result?',requirementTag:input.category.toUpperCase()};}
export function localChat(message:string,context=''){const a=localAnalyzeResponse({text:(message+'\n'+context).trim()});return['### ReqVoice Local AI Analysis','','**Mode:** Offline local requirements analysis','**Model:** '+LOCAL_MODEL,'','**Sentiment:** '+a.sentiment+' ('+a.sentimentScore.toFixed(2)+')','**Urgency:** '+a.urgency,'','**Potential requirements / investigation points:**',...(a.keyRequirements.length?a.keyRequirements.slice(0,5).map(r=>'- '+r):['- No strong requirement marker detected; ask a clarifying question.']),'','**Suggested next probe:** '+localRealtimeCopilot({questionText:message,currentAnswer:context,category:'requirement'}).clarifyingProbe].join('\n');}
export function localGuide(systemName:string,role:string){const q=localSuggestQuestions({systemName,role,count:5,interviewType:'Semi-Structured'}).questions;return{guide:{id:'local-guide-'+Date.now(),systemId:'offline',role,title:'Offline Interview Guide — '+systemName,phases:[{name:'Context',durationMinutes:5,questions:q.slice(0,2).map(x=>x.questionText),tips:'Clarify the stakeholder role and current workflow.'},{name:'Pain Points',durationMinutes:10,questions:q.slice(2,4).map(x=>x.questionText),tips:'Ask for concrete examples and measurable impact.'},{name:'Future State',durationMinutes:10,questions:q.slice(4).map(x=>x.questionText),tips:'Confirm priorities, constraints, and acceptance expectations.'}]}};}
export function localCrossCompare(interviews:InterviewSession[]){const texts=interviews.flatMap(i=>Object.values(i.responses||{}).map(r=>r.responseText||'')).filter(Boolean);const a=localAnalyzeResponse({text:texts.join('\n')||'No responses recorded.'});return{comparison:{modelUsed:LOCAL_MODEL,interviewCount:interviews.length,responseCount:texts.length,commonThemes:a.keyRequirements,overallSentiment:a.sentiment,urgency:a.urgency,generatedAt:new Date().toISOString()}};}
export function localTranscriptionFallback(questionText:string){return{transcript:'Offline media transcription requires a local speech model. Reconnect for full Gemini speech-to-text, or enter the response text manually.',confidence:0,sentiment:'neutral' as const,sentimentScore:0,keyRequirements:['Reconnect for full speech-to-text transcription for: '+questionText],modelUsed:LOCAL_MODEL,generatedAt:new Date().toISOString()};}
export const LOCAL_AI_MODELS=[{id:LOCAL_MODEL,name:'ReqVoice Local AI',provider:'On-device',tagline:'Offline requirements analysis and interview assistance',speed:'Instant',contextWindow:'Local browser storage',recommended:false}];
